### ISSUE TITLE
Service not running but the broker is working

### ISSUE THREAD

**Issue by adorobis** [tprelog/iocage-mosquitto#6]
Hi,
I know it is not maintained but I have a strange problem with it. The service is not running but there is a mosquitto process and all works fine also after jail restart. I could ignore it but can't upgrade the jail as after that the process does not start after jail restart. How come the process is running but service not? Where should I look for any traces/logs?
```
root@homeserwer:~ # iocage console mqtt
Last login: Fri Dec 10 15:06:47 on pts/0
FreeBSD 12.2-RELEASE-p11 75566f060d4(HEAD) TRUENAS

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          Mosquitto - FreeNAS Community Plugin
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
- edit mosquitto config file:
    ee /usr/local/etc/mosquitto/mosquitto.conf

- control mosquitto service:
    service mosquitto [reload|restart|start|status|stop]

- testing subscribe or publish:
    mosquitto_sub -d -t /dev/test
    mosquitto_pub -d -t /dev/test -m "Hello World"
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
root@mqtt:~ # service mosquitto status
mosquitto is not running.
root@mqtt:~ # ps -ax
  PID TT  STAT    TIME COMMAND
91196  -  SsJ  0:00.02 /usr/sbin/syslogd -c -ss
91237  -  SsJ  0:05.10 /usr/local/sbin/mosquitto -c /usr/local/etc/mosquitto/mosquitto.conf -d
91287  -  SsJ  0:00.03 /usr/sbin/cron -J 15 -s
37242  0  SJ   0:00.01 login [pam] (login)
37243  0  SJ   0:00.02 -csh (csh)
37259  0  R+J  0:00.00 ps -ax
```

**Comment by tprelog** [comment]
@adorobis - That's very strange indeed.

What happens if you `kill` the running process, then start it and check the status.
```
kill 91237
service mosquitto start
service mosquitto status
```

---

> I know it is not maintained

Really, it's just that I'm currently trying out TN SCALE. I'll still do my best to resolve any issues when they are reported. I'm just not going to catching them myself because I'm not running TN CORE atm.

I'll try to get a VM with CORE fired up and have a look if I can reproduce this

**Comment by adorobis** [comment]
Thanks for quick response. 
> What happens if you `kill` the running process, then start it and check the status.

Yeah, I've tried it in the first place. The process shows up as working but I can't connect to it.

I've actually installed the plugin from scratch and it is working as expected. So I've switched to it, probably waste of time to try to analyse it. It is the beauty of mqtt that such replacement is so easy :)

**Comment by adorobis** [comment]
@tprelog  btw, how is it going with the SCALE? Have you migrated existing CORE install or started from scratch? And for HA (and other components, like MQTT zigbee, zwave) which installation method have you selected? Docker or VM?
Is there a discussion forum where this could be (or already is) discussed?

**Comment by tprelog** [comment]
> how is it going with the SCALE?

I've had good luck with SCALE so far, but I'm still not sure if I will stick with it or move back to CORE.

> Have you migrated existing CORE install or started from scratch?

I switched before the migration wizard was released so I basically started from scratch. I did however import my existing pools. I also left the entire iocage dataset intact. I created a new dataset to store the configuration used by the containers, and copied existing config from iocage dataset to the new one.

> which installation method have you selected? Docker or VM?

I'm one of _those_ people who has decided to take the risk of using docker directly. I'm not using any "apps" from the SCALE UI. I wrote a small post-init script that overwrites the default docker daemon.json with my own, and starts the docker.service. To manage my containers, I'm just using docker-compose. I've also opted to use macvlan so I could assign each containers it's own ip address on my network. I found this to be a quick and easy way of switching my jails to containers, with minimal changes to my setup. Unfortunately, it's completely unsupported by SCALE.

> Is there a discussion forum where this could be (or already is) discussed?

Depends on exactly what your referring to...

**Comment by adorobis** [comment]
Great, thanks for sharing your experience. As I don't have a spare hardware I'll wait a bit until SCALE is settled and migration path clear (also if clean install is a better option).
Regarding forum I mean where people would share experience with migrating from CORE.

**Comment by tprelog** [comment]
> Regarding forum I mean where people would share experience with migrating from CORE.

Definitely on the TrueNAS Forum... And if you're planning to run containers (aka "Apps") in a supported manner and directly on SCALE, it's likely worth joining the [TrueCharts discord channel](https://truecharts.org/discord) to follow along with user experience there as well.
